version: '3.7'

services:
  app:
    image: codehq-ui/app
    build:
      context: ./client/docker/dev
      args:
        UID: ${DEV_UID-501}
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    environment:
      - HOST=0.0.0.0
